# This is a basic workflow to help you get started with Actions

name: Trigger

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: benchmark.yaml
          repo: Eternal-Night-Archer/BenchmarkData
          token: ${{ secrets.PAT }}
          inputs: '{ "repository": "https://github.com/Eternal-Night-Archer/BenchmarkTrigger", "pr_id": "1", "url": "https://github.com/Eternal-Night-Archer/BenchmarkTrigger/pull/1" }'
